### ISSUE TITLE
Backend - Create schema rough draft

### ISSUE THREAD

**Issue by ZzRanger** [ZzRanger/Compass#9]
**Tasks**
- [x] Draft product requirements (Caleb will be doing this)
- [x] Decide on database. This will likely determine the structure of your schema
- [x] Draft schema rough draft
